spring:
  datasource:
    url: jdbc:h2:mem:cinema-db;DATABASE_TO_LOWER=TRUE
    driver-class-name: org.h2.Driver
    username: sa
    password: password
  jpa:
    database-platform: org.hibernate.dialect.H2Dialect
    properties:
      hibernate:
        ddl-auto: none
        globally_quoted_identifiers: true
  liquibase:
    change-log: liquibase/changelog.yml
